# Generated by Django 4.0.1 on 2022-10-05 08:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product', models.CharField(max_length=200)),
                ('Rating', models.IntegerField()),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Accounts.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Laptop',
            fields=[
                ('date', models.DateField(auto_now_add=True)),
                ('Name', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('Desc', models.TextField()),
                ('Price', models.IntegerField()),
                ('Choice', models.CharField(choices=[('1', 'Gaming'), ('2', 'Workstation'), ('3', 'Domestic')], max_length=1)),
                ('Image1', models.URLField()),
                ('Image2', models.URLField()),
                ('Image3', models.URLField()),
                ('Image4', models.URLField()),
                ('Image5', models.URLField()),
                ('CPU', models.CharField(choices=[('1', 'Intel'), ('2', 'AMD')], max_length=1)),
                ('CPU_MODEL', models.CharField(max_length=100)),
                ('RAM', models.CharField(choices=[('1', 'DDR3'), ('2', 'DDR4')], max_length=1)),
                ('RAM_SPEED', models.CharField(max_length=100)),
                ('GPU', models.CharField(choices=[('1', 'Nvidia'), ('2', 'AMD')], max_length=2)),
                ('GPU_Model', models.CharField(max_length=100)),
                ('SSD', models.BooleanField(blank=True, null=True)),
                ('SSD_BRAND', models.CharField(max_length=100)),
                ('HDD', models.CharField(choices=[('1', '2 TB'), ('2', '1 TB')], max_length=1)),
                ('HDD_BRAND', models.CharField(max_length=100)),
                ('RefreshRate', models.CharField(max_length=10)),
                ('OS', models.CharField(max_length=100)),
                ('WARRANTY', models.CharField(max_length=100)),
                ('Dealer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Accounts.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Desktop',
            fields=[
                ('date', models.DateField(auto_now_add=True)),
                ('Name', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('Desc', models.TextField()),
                ('Price', models.IntegerField()),
                ('Choice', models.CharField(choices=[('1', 'Gaming'), ('2', 'Workstation'), ('3', 'Domestic')], max_length=1)),
                ('Image1', models.URLField()),
                ('Image2', models.URLField()),
                ('Image3', models.URLField()),
                ('Image4', models.URLField()),
                ('Image5', models.URLField()),
                ('CPU', models.CharField(choices=[('1', 'Intel'), ('2', 'AMD')], max_length=1)),
                ('CPU_MODEL', models.CharField(max_length=100)),
                ('RAM', models.CharField(choices=[('1', 'DDR3'), ('2', 'DDR4')], max_length=1)),
                ('RAM_SPEED', models.CharField(max_length=100)),
                ('GPU', models.CharField(choices=[('1', 'Nvidia'), ('2', 'AMD')], max_length=2)),
                ('GPU_Model', models.CharField(max_length=100)),
                ('SSD', models.BooleanField(blank=True, null=True)),
                ('SSD_BRAND', models.CharField(blank=True, max_length=100, null=True)),
                ('HDD', models.CharField(choices=[('1', '2 TB'), ('2', '1 TB')], max_length=1)),
                ('HDD_BRAND', models.CharField(max_length=100)),
                ('RefreshRate', models.CharField(max_length=10)),
                ('OS', models.CharField(max_length=100)),
                ('WARRANTY', models.CharField(max_length=100)),
                ('Dealer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Accounts.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('Id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('Comment', models.CharField(max_length=150)),
                ('Product', models.CharField(max_length=150)),
                ('Date', models.DateTimeField(auto_now_add=True, null=True)),
                ('Upvotes', models.IntegerField()),
                ('Downvotes', models.IntegerField()),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Accounts.profile')),
            ],
        ),
    ]
