# Generated by Django 2.2.5 on 2020-05-23 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DB', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='desktop',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
