# Generated by Django 2.2.5 on 2020-05-31 05:23

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DB', '0002_auto_20200530_2016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='desktop',
            name='Image1',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='Image1'),
        ),
        migrations.AlterField(
            model_name='desktop',
            name='Image2',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='Image2'),
        ),
        migrations.AlterField(
            model_name='desktop',
            name='Image3',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='Image3'),
        ),
        migrations.AlterField(
            model_name='desktop',
            name='Image4',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='Image4'),
        ),
        migrations.AlterField(
            model_name='desktop',
            name='Image5',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='Image5'),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='Image1',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='Image1'),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='Image2',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='Image3',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='Image4',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='Image5',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='Image'),
        ),
    ]
