# Generated by Django 2.2.5 on 2020-05-31 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DB', '0004_auto_20200531_1054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='desktop',
            name='Image1',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='desktop',
            name='Image2',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='desktop',
            name='Image3',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='desktop',
            name='Image4',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='desktop',
            name='Image5',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='Image1',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='Image2',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='Image3',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='Image4',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='Image5',
            field=models.URLField(),
        ),
    ]
