# Generated by Django 2.2.5 on 2020-07-27 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WishList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Class', models.CharField(choices=[('1', 'Desktop'), ('2', 'Laptop')], max_length=1)),
                ('SubClass', models.CharField(choices=[('1', 'Gaming'), ('2', 'Workstation'), ('3', 'Domestic')], max_length=1)),
            ],
        ),
    ]
