# Generated by Django 2.2.5 on 2020-07-27 18:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product_Name', models.CharField(max_length=200)),
                ('Price', models.IntegerField()),
                ('Timestamp', models.DateTimeField(auto_now_add=True)),
                ('Order_id', models.CharField(blank=True, max_length=120, null=True)),
                ('Status', models.CharField(choices=[('1', 'Not Yet Shipped'), ('2', 'Shipped'), ('3', 'Cancelled'), ('4', 'Refunded'), ('5', 'Refund Requested')], default='1', max_length=1)),
                ('Dealer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='Dealer', to='Accounts.Profile')),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='User', to='Accounts.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='Carts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateTimeField(auto_now_add=True)),
                ('Item', models.CharField(max_length=100)),
                ('Price', models.IntegerField()),
                ('Ordered', models.BooleanField(default=False)),
                ('Date_Ordered', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Accounts.Profile')),
            ],
        ),
    ]
