# Generated by Django 2.2.5 on 2020-05-23 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carts',
            name='Date_Ordered',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
