# Generated by Django 2.2.5 on 2020-05-23 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0002_auto_20200523_1308'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='Delivered',
        ),
        migrations.AddField(
            model_name='orders',
            name='Status',
            field=models.CharField(choices=[('1', 'Not Yet Shipped'), ('2', 'Shipped'), ('3', 'Cancelled'), ('4', 'Refunded')], default='1', max_length=1),
        ),
        migrations.AlterField(
            model_name='orders',
            name='Order_id',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
