# Generated by Django 2.2.5 on 2020-05-23 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0003_auto_20200523_1816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='Order_id',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
