# Generated by Django 2.2.5 on 2020-05-23 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0004_auto_20200523_1826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='Status',
            field=models.CharField(choices=[('1', 'Not Yet Shipped'), ('2', 'Shipped'), ('3', 'Cancelled'), ('4', 'Refunded'), ('5', 'Refund Requested')], default='1', max_length=1),
        ),
    ]
